trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
- group: Docker Shared variables
- group: APPLY - Production Secrets
- name: imageName
  value: 'apply-for-postgraduate-teacher-training'
- name: defaultProviderEmail
  value: 'email@example.com'
- name: debug
  value: true

stages:
- stage: build_test_release
  displayName: 'Build, Test & Release'
  jobs:
  - job: build_and_test_docker_image
    displayName: 'Build & Test Docker Image'
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
    - name: system.debug
      value: $(debug)

    steps:
    - script: |
        GIT_SHORT_SHA=$(echo $(Build.SourceVersion) | cut -c 1-7)
        docker_path=$(dockerHubUsername)/$(imageName)
        echo '##vso[task.setvariable variable=compose_file]docker-compose.yml:docker-compose.azure.yml'
        echo "##vso[build.updatebuildnumber]$GIT_SHORT_SHA"
        echo "##vso[task.setvariable variable=docker_path;]$docker_path"
      displayName: 'Set version number'

    - script: make setup
      displayName: 'Build & setup'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        railsSecretKeyBase: $(railsSecretKeyBase)
        RAILS_ENV: production
        DEFAULT_PROVIDER_EMAIL: $(defaultProviderEmail)
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)

    - script: |
        docker-compose run --rm web bundle exec rake db:setup
        make ci.lint-ruby
      displayName: 'Rubocop'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        DEFAULT_PROVIDER_EMAIL: $(defaultProviderEmail)
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)

    - script: make ci.lint-erb
      displayName: 'ERB lint'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        DEFAULT_PROVIDER_EMAIL: $(defaultProviderEmail)
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)

    - script: |
        make ci.test
        test_result=$?
        if [ "$test_result" == "0" ]; then true; else cat rspec-results.xml; false; fi
      displayName: 'Execute tests'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        DEFAULT_PROVIDER_EMAIL: $(defaultProviderEmail)
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)

    - task: Docker@1
      displayName: Tag image with current build number $(Build.BuildNumber)
      inputs:
        command: Tag image
        imageName: "$(docker_path):latest"
        arguments: "$(docker_path):$(Build.BuildNumber)"

    - task: Docker@1
      displayName: Docker Hub login
      inputs:
        command: "login"
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: DfE Docker Hub

    - task: Docker@1
      displayName: Push tagged image
      inputs:
        command: Push an image
        imageName: "$(docker_path):$(Build.BuildNumber)"

    - task: Docker@1
      displayName: Push tagged image (latest) if master
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: Push an image
        imageName: "$(docker_path):latest"

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifacts'
      inputs:
        path: '$(System.DefaultWorkingDirectory)/azure/'
        artifactName: 'arm_template'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: 'rspec-results.xml'


- stage: deploy_dev
  displayName: 'Deploy - Development'
  dependsOn: build_test_release
  condition: and(succeeded('build_test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: azure-pipelines-deploy-template.yml
    parameters:
      debug: $(debug)
      subscriptionPrefix: 's106'
      subscriptionName: 'Apply (106) - Dev'
      environment: 'development'
      resourceEnvironmentName: 'd01'
      serviceName: 'apply'
      containerImageReference: '$(imageName):$(build.buildNumber)'
      databaseName: 'apply'
      databaseUsername: 'applyadm512'
      databasePassword: '$(databasePassword)'
      dockerhubUsername: '$(dockerHubUsername)'
      railsSecretKeyBase: '$(railsSecretKeyBase)'
      railsEnv: 'production'


- stage: deploy_test
  displayName: 'Deploy - Test'
  dependsOn: build_test_release
  condition: and(succeeded('build_test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: azure-pipelines-deploy-template.yml
    parameters:
      debug: $(debug)
      subscriptionPrefix: 's106'
      subscriptionName: 'Apply (106) - Test'
      environment: 'test'
      resourceEnvironmentName: 't01'
      serviceName: 'apply'
      containerImageReference: '$(imageName):$(build.buildNumber)'
      databaseName: 'apply'
      databaseUsername: 'applyadm512'
      databasePassword: '$(databasePassword)'
      dockerhubUsername: '$(dockerHubUsername)'
      railsSecretKeyBase: '$(railsSecretKeyBase)'
      railsEnv: 'production'


# - stage: deploy_production
#   displayName: 'Deploy - Production'
#   dependsOn: build_test_release
#   condition: and(succeeded('build_test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   variables:
#     value: 'email@example.com'
#   jobs:
#   - template: azure-pipelines-deploy-template.yml
#     parameters:
#       debug: $(debug)
#       subscriptionPrefix: 's106'
#       subscriptionName: 'Apply (106) - Production'
#       environment: 'production'
#       resourceEnvironmentName: 'p01'
#       serviceName: 'apply'
#       containerImageReference: '$(imageName):$(build.buildNumber)'
#       databaseName: 'apply'
#       databaseUsername: 'applyadm512'
#       databasePassword: '$(databasePassword)'
#       dockerhubUsername: '$(dockerHubUsername)'
#       railsSecretKeyBase: '$(railsSecretKeyBase)'
#       railsEnv: 'development'
