version: "3.6"
services:
  web:
    build:
      target: production
      args:
        bundleWithout: 'development'
        BASE_RUBY_IMAGE_WITH_GEMS_AND_NODE_MODULES: ${gemsNodeModulesImageName:-apply-for-teacher-training-gems-node-modules}
    image: ${dockerHubUsername}/${dockerHubImageName}:${dockerHubImageTag}
    environment:
      - RAILS_ENV
      - SERVICE_TYPE
      - GOVUK_NOTIFY_API_KEY
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - SECRET_KEY_BASE=${railsSecretKeyBase}
      - AUTHORISED_HOSTS
      - SENTRY_DSN
      - LOGSTASH_ENABLE
      - LOGSTASH_REMOTE
      - LOGSTASH_HOST
      - LOGSTASH_PORT
      - LOGSTASH_SSL
      - STATE_CHANGE_SLACK_URL
      - DSI_API_URL
      - DSI_API_SECRET
      - SANDBOX
