version: "3.6"
services:
  web:
    build:
      target: prod-build
      args:
        bundleWithout: 'development'
    image: ${dockerHubUsername}/${dockerHubImageName}:latest
    environment:
      - RAILS_ENV
      - SERVICE_TYPE
      - GOVUK_NOTIFY_API_KEY
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - SUPPORT_USERNAME
      - SUPPORT_PASSWORD
      - SECRET_KEY_BASE=${railsSecretKeyBase}
      - AUTHORISED_HOSTS
      - SENTRY_DSN
      - LOGSTASH_ENABLE
      - LOGSTASH_REMOTE
      - LOGSTASH_HOST
      - LOGSTASH_PORT
      - LOGSTASH_SSL
      - STATE_CHANGE_SLACK_URL
      - DSI_API_URL
      - DSI_API_SECRET
      - SANDBOX
