Layout/LineLength:
  Enabled: false

# Disable these cops because they do not allow reasonable code like splitting
# `attr_reader :bla, :foo` over 2 lines.
Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: false
