Naming/MethodParameterName:
  AllowedNames:
    - e
    - to

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: true
  Exclude:
    - app/models/teacher_training_public_api/sync_check.rb
    - app/services/ucas_matching/file_download_check.rb
    - app/controllers/candidate_interface/candidate_interface_controller.rb

Naming/PredicateName:
  Enabled: true

Naming/VariableNumber:
  Enabled: false
