---
:shared:
  :notifications:
  - id
  - notified_type
  - notified_id
  - notification_type
  - created_at
  - updated_at
  :emails:
  - application_form_id
  - created_at
  - delivery_status
  - id
  - mail_template
  - mailer
  - notify_reference
  - to
  - body
  - subject
  - updated_at
  :vendor_api_requests:
  - id
  - request_path
  - request_method
  - status_code
  - request_headers
  - request_body
  - response_body
  - provider_id
  - response_headers
  - created_at
  :provider_pool_actions:
  - id
  - status
  - application_form_id
  - actioned_by_id
  - recruitment_cycle_year
  - created_at
  - updated_at
  :candidate_pool_applications:
  - application_form_id
  - candidate_id
  - id
  - created_at
  - updated_at
  - study_mode_full_time
  - study_mode_part_time
  - needs_visa
  - course_type_postgraduate
  - course_type_undergraduate
  - subject_ids
  - rejected_provider_ids
  - course_funding_type_fee
  :sessions:
  - id
  - candidate_id
  - ip_address
  - user_agent
  - id_token_hint
  - error_message
  - created_at
  - updated_at
  :session_errors:
  - id
  - candidate_id
  - id_token_hint
  - body
  - omniauth_hash
  - created_at
  - updated_at
  - error_type
  :audits:
  - id
  - auditable_id
  - auditable_type
  - associated_id
  - associated_type
  - user_id
  - user_type
  - username
  - action
  - audited_changes
  - version
  - comment
  - remote_address
  - request_uuid
  - created_at
  :active_storage_variant_records:
  - id
  - blob_id
  - variation_digest
  - created_at
  :active_storage_blobs:
  - id
  - key
  - filename
  - content_type
  - metadata
  - service_name
  - byte_size
  - checksum
  - created_at
  :active_storage_attachments:
  - id
  - name
  - record_type
  - record_id
  - blob_id
  - created_at
  :blazer_queries:
  - id
  - creator_id
  - name
  - description
  - statement
  - data_source
  - status
  - created_at
  - updated_at
  :blazer_dashboard_queries:
  - id
  - dashboard_id
  - query_id
  - position
  - created_at
  - updated_at
  :blazer_dashboards:
  - id
  - creator_id
  - name
  - created_at
  - updated_at
  :blazer_checks:
  - id
  - creator_id
  - query_id
  - state
  - schedule
  - emails
  - slack_channels
  - check_type
  - message
  - last_run_at
  - created_at
  - updated_at
  :blazer_audits:
  - id
  - user_id
  - query_id
  - statement
  - data_source
  - created_at
  :monthly_statistics_reports:
  - id
  - created_at
  - updated_at
  - statistics
  - month
  - generation_date
  - publication_date
  :provider_recruitment_performance_reports:
  - id
  - provider_id
  - statistics
  - cycle_week
  - publication_date
  - generation_date
  - created_at
  - updated_at
  - recruitment_cycle_year
  :national_recruitment_performance_reports:
  - id
  - statistics
  - cycle_week
  - publication_date
  - generation_date
  - created_at
  - updated_at
  - recruitment_cycle_year
  :vendor_api_users:
  - id
  - full_name
  - email_address
  - vendor_user_id
  - vendor_api_token_id
  - created_at
  - updated_at
  :vendor_api_tokens:
  - hashed_token
  :validation_errors:
  - details
  :support_users:
  - id
  - dfe_sign_in_uid
  - created_at
  - updated_at
  - email_address
  - last_signed_in_at
  - first_name
  - last_name
  - discarded_at
  :provider_user_notifications:
  - chase_provider_decision
  :provider_users:
  - find_a_candidate_filters
  :providers:
  - phone_number
  :one_login_auths:
  - token
  :interviews:
  - additional_details
  - cancellation_reason
  :find_feedback:
  - email_address
  :features:
  - id
  - name
  - active
  - created_at
  - updated_at
  :english_proficiencies:
  - no_qualification_details
  :fraud_matches:
  - id
  - candidate_last_contacted_at
  - recruitment_cycle_year
  - last_name
  - date_of_birth
  - postcode
  - blocked
  - created_at
  - updated_at
  - resolved
  :data_migrations:
  - id
  - service_name
  - timestamp
  - created_at
  - updated_at
  :data_exports:
  - id
  - name
  - data
  - completed_at
  - initiator_type
  - initiator_id
  - created_at
  - updated_at
  - export_type
  :authentication_tokens:
  - id
  - hashed_token
  - created_at
  - updated_at
  - user_id
  - user_type
  - used_at
  - path
  :references:
  - email_address
  - name
  - relationship
  - safeguarding_concerns
  - relationship_correction
  :application_forms:
  - address_line1
  - address_line2
  - address_line3
  - address_line4
  - subject_knowledge
  - safeguarding_issues
  - subject_knowledge_completed
  - address_type
  - latitude
  - longitude
  - subject_knowledge_completed_at
  - feedback_form_complete
  :application_choices:
  - provider_ids
  - current_recruitment_cycle_year
  - decline_by_default_at
  - decline_by_default_days
  :account_recovery_request_codes:
  - code_digest
  :account_recovery_requests:
  - previous_account_email_address
  :site_settings:
  - id
  - name
  - value
  - created_at
  - updated_at
  :candidates:
  - magic_link_token
  - fraud_match_id
  - unsubscribed_from_emails
  - submission_blocked
  - account_locked
  :provider_user_filters:
  - id
  - provider_user_id
  - kind
  - pagination_page
  - filters
  - created_at
  - updated_at
  :deferred_offer_confirmations:
  - id
  - provider_user_id
  - offer_id
  - course_id
  - site_id
  - study_mode
  - conditions_status
  - created_at
  - updated_at
  - offered_course_option_id
  :sites:
  - latitude
  - longitude
