development: &default
  ABC:
    - 'ABC' # Set this as the UID when bypassing DfE Sign-in to see applications for provider code ABC

production:
  1N1:
    - '5A992CD2-DEE2-4A8A-9EC3-82BE6E22B161' # SF (test)
    - '85802F1B-3E84-4D1A-9920-3751CD150B60' # JA (test)
    - 'BF009778-B687-4224-B1E9-2909B77FA4DA' # ML (test)
    - 'F55735E8-3076-401C-9684-8EBAFCB2D853' # JB (test)
