development: &default
  codes:
    - 1HQ  # Alliance of Leading Learning
    - 24L  # Ashton on Mersey SCITT
    - 1N1  # Gorse SCITT
    - 254  # Nottinghamshire Torch SCITT
    - 2LR  # Oriel High School
    - R55  # Royal Academy of Dance
    - L06  # Shotton Hall SCITT
    - S31  # Somerset SCITT Consortium
    - 12K  # Trent Valley Teaching School Alliance
    - D87  # Durham SCITT
    - N83  # North West Shares SCITT
    - 1OT  # The Academy at Shotton Hall

production:
  <<: *default
