development: &default
  ABC:
    - "ABC" # Set this as the UID when bypassing DfE Sign-in to see applications for provider code ABC

production:
  1N1:
    - "5A992CD2-DEE2-4A8A-9EC3-82BE6E22B161" # SF (test)
    - "85802F1B-3E84-4D1A-9920-3751CD150B60" # JA (test)
    - "BF009778-B687-4224-B1E9-2909B77FA4DA" # ML (test)
    - "F55735E8-3076-401C-9684-8EBAFCB2D853" # JB (test)
    - "159DCD78-64CE-47D0-8C4C-DF4DF2DB5705" # PV (test, can remove after 17/12/2019)
    - "11496782-C686-4C61-8A3D-593844183031" # JB (test, DAC can remove after 22/12/2019)
    - "11252B7F-917A-4511-97E7-6A3F7BCD4F6A" # TV (test)
    - "80F38C12-886C-4052-BCDD-20A3199B2752"
    - "74991804-FD2E-426A-BB0C-BB542E13599E"
    - "E3CCD08C-7DD5-4BE5-B3B0-A4BE735C81EA"
  24L:
    - "97574973-C4F3-4682-81ED-6184ECC89B7A"
    - "C7904341-4357-47B3-AC55-D2C66B553ECF"
  2LR:
    - "1B85E1E7-9211-4162-9335-B1F3AAB96144"
    - "9EFF899B-793D-418C-94C4-8500CF2DBC58"
  D87:
    - "52A93D3A-E7D7-4917-B58D-156F8020BF16"
    - "85FCDBD7-92CA-41A1-975B-40418D62CEA9"
  N83:
    - "3A11120D-F707-4CD1-B014-045857AD5229"
    - "A1C0545B-F5FF-4045-B6B1-EC5D77A7A1CE"
  12K:
    - "CF996A80-3C7E-4BD3-8FC7-AD6B05DD99AB"
  "254":
    - "03812769-AFF4-41BF-AB34-CC7EFE756583"
  R55:
    - "FBB2073F-1C20-4B59-AAD0-8098D5108AFA"
  S31:
    - "E33EC234-0F89-42ED-88D7-5B93DB741F8C"
    - "8772E175-955C-4954-80CC-C84372C2BEB5"
  1HQ:
    - "E09B78BB-2521-45D1-9389-618C8967EBD7"
    - "8D1ED6F2-E831-4C4C-9EDE-435423018CF0"
  L06:
    - "C44F82CC-0A16-48AC-AC03-6A0EB363FDBE"
    - "1079EE05-7616-48F0-99C4-505B892679BD"
