---
#The authentication token for the application
authentication: <%= ENV.fetch('SKYLIGHT_AUTH_TOKEN') %>
enable_sidekiq: true
deploy:
  git_sha: <%= ENV['SHA'] %>
ignored_endpoints:
  - HealthcheckController#show
agent:
  sockfile_path: /tmp/apply-for-postgraduate-teacher-training
