name: Restore Database from Azure To PaaS

on:
  workflow_dispatch:
  schedule: # 03:00 UTC Mon-Fri
    - cron: '0 3 * * 1-5'

jobs:
  backup:
    name: Restore Database
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [production]
        include:
         - environment: production
           NAME_SUFFIX: prod
    environment:
      name: ${{ matrix.environment }}
    steps:
    - name: Setup cf cli 
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME:   ${{ secrets.CF_USERNAME }}
        CF_PASSWORD:   ${{ secrets.CF_PASSWORD }}
        CF_SPACE_NAME: ${{ secrets.CF_SPACE }}
        INSTALL_CONDUIT: true

    - name: Setup postgres client
      uses: DFE-Digital/github-actions/install-postgres-client@master
        
    - name: Backup Azure DB
      run: pg_dump -E utf8 --clean --no-owner --verbose --no-password -d ${{ secrets.AZURE_DATABASE_NAME }} -f db_backup_${{ matrix.environment }}.sql
      env:
        PGHOST:     ${{ secrets.AZURE_DATABASE_HOST }}
        PGUSER:     ${{ secrets.AZURE_DATABASE_USER }}
        PGPASSWORD: ${{ secrets.AZURE_DATABASE_PASSWORD }}

    - name: Restore Azure DB to PaaS ${{ matrix.environment }}
      run: cf conduit ${POSTGRES_SERVICE_INSTANCE} -- psql < db_backup_${{ matrix.environment }}.sql
      env:
        POSTGRES_SERVICE_INSTANCE: apply-postgres-${{ matrix.NAME_SUFFIX || matrix.environment }}
